server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com
  client:
    # 不拉取其它服务
    fetch-registry: false
    # 不像服务端注册自己 因为本身就是服务器
    register-with-eureka: false
    # eureka的服务地址 单机版
    # service-url:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #集群版则需要服务器向集群的机器互相注册 形成互相观望的状态 7001 7002 7003 三台机子 则 7001中向7002 7003注册 7002向7001 7003注册
    service-url:
      defaultZone: http://localhost:7001/eureka/
