server:
  port: 9527
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: gateway-helloGateway
          uri: http://www.baidu.com
          predicates:
            - After=2023-04-12T23:52:44.163+08:00[Asia/Shanghai]